#!/bin/sh
#
# Copyright (c) 2009 Daniel Gryniewicz
#
# Clean up a git checkout to match it's repo

# Set usage output
USAGE="[-h |--help]"
LONGUSAGE="Clean up a git checkout to match it's repo
\t-h, --help\n\t\tPrint this help message"

# Standard functions
GTWSLOC=$(readlink -f $(dirname "$0"))
source ${GTWSLOC}/gtws.sh

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o h --long help -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal

SUBDIRECTORY_OK=Yes
OPTIONS_SPEC=
LONG_USAGE="${LONGUSAGE}"
# Source the git environment
source "$(git --exec-path)/git-sh-setup"

git checkout .
git status | grep "^\#	" | sed 's/#\t//' | xargs rm -r
