#!/bin/bash
#
# Start or attach to a tmux session in a workspace
#

GATED="trunk"

# Set usage output
USAGE="[-h |--help] [-v <version> | --version=<version>] <name>"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t-v <version>, --version=<version>\n\t\tGateD version (default: ${GATED})
\t<name>\n\t\tWorkspace name"

# Standard functions
GTWSLOC=$(readlink -f $(dirname "$0"))
source ${GTWSLOC}/gtws.sh

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o hv: --long help,version: -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		-v|--version) GATED=$2 ; shift 2 ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal
if [ -z "${1}" ]; then
	usage "Must give a workspace name"
fi

NAME="${1}"

if [ ! -f ${HOME}/src/${GATED}/${NAME}/.gtwsrc ]; then
	usage "No env for ${GATED}/${NAME}"
fi

exec bash --rcfile ${HOME}/src/${GATED}/${NAME}/.gtwsrc
