#!/bin/bash
#
# Config file for gtws.  Should be sourced into your shell.
#
# Cascades up the path, loading any config it finds.  Each more specific config
# file overrides less specific ones.

if [ -n "${GTWS_WS_GUARD}" ]; then
	debug_print "WS Already loaded"
	return
fi
export GTWS_WS_GUARD="yes"

# Things expected to come from a higher .gtwsrc:
# GTWS_PROJECT - Name of project
# GTWS_PROJECT_VERSION - Version of project
#
# Optional settings:
# GTWS_ORIGIN - Path to origin directory. Defaults to ${HOME}/origin
# GTWS_SETPROMPT - Set the shell prompt to the workspace name

export GTWS_WSPATH=$(readlink -f ${BASH_ARGV[0]%/*})
export GTWS_WSNAME=$(basename "${GTWS_WSPATH}")
export GTWS_PREFIX="${GTWS_WSPATH}/install"

source ${GTWS_LOC}/gtws.sh
debug_print "Loading WS"

__gtws_prompt_command() {
  printf "\033]0;%s:%s\007" "${GTWS_PROMPT}" "${PWD/#$HOME/~}"
}

# title "foobar"
#
# Set the xterm/gnome-terminal title
function title {
	export GTWS_PROMPT="$1"
	export PROMPT_COMMAND="__gtws_prompt_command"
	#echo -en "\033]2;$(__gtws_prompt_command)\007"
}

# Load config files
load_rc ${GTWS_WSPATH}

# Override env if we're in docker
DOCKER_ENV=".gtwsrc_docker"
if is_docker ; then
	source "${GTWS_WSPATH}/${DOCKER_ENV}"
fi

if [ -z "${GTWS_SAVEPATH}" ]; then
	export GTWS_SAVEPATH="${PATH}"
fi
PATH="${GTWS_SAVEPATH}:${GTWS_PREFIX}/bin:${GTWS_PREFIX}/sbin"
if [ -n "${GTWS_PATH_EXTRA}" ]; then
	PATH=${PATH}:"${GTWS_PATH_EXTRA}"
fi
export PATH

export CDPATH=":$GTWS_WSPATH"

title "${GTWS_PROJECT}:${GTWS_PROJECT_VERSION}:${GTWS_WSNAME}"

if [ -z "${GTWS_SAVEPS1}" ]; then
	export GTWS_SAVEPS1="${PS1}"
fi
if [ -n "${GTWS_SETPROMPT}" ]; then
	#PROMPT="($GTWS_PROJECT"
	#if [ "$GTWS_PROJECT_VERSION" != "trunk" ]; then
		#PROMPT="${PROMPT}:${GTWS_PROJECT_VERSION}"
	#fi
	#PROMPT="${PROMPT}:${GTWS_WSNAME})"
	PROMPT="(${GTWS_WSNAME})"
fi
PS1="${PROMPT}${GTWS_SAVEPS1}"

# Make bashmarks local to the workspace and persistent
SDIRS="${GTWS_WSPATH}/.sdirs"

# Make things installed locally be runnable
if [ -n "${GTWS_LD_LIBRARY_PATH}" ] ; then
	export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GTWS_LD_LIBRARY_PATH}"
fi
if [ -n "${GTWS_PYTHONPATH}" ] ; then
	export PYTHONPATH="${PYTHONPATH}:${GTWS_PYTHONPATH}"
fi

# Local settings go here
