#!/bin/bash
#
# Config file for gtws.  Should be sourced into your shell.
#
# Cascades up the path, loading any config it finds.  Each more specific config
# file overrides less specific ones.

# Things expected to come from a higher .gtwsrc:
# GTWS_PROJECT - Name of project
# GTWS_PROJECT_VERSION - Version of project
#
# Optional settings:
# GTWS_ORIGIN - Path to origin directory. Defaults to ${HOME}/origin
# GTWS_SETPROMPT - Set the shell prompt to the workspace name

WSPATH=$(readlink -f ${BASH_ARGV[0]%/*})
WSNAME=$(basename "${WSPATH}")


# load_rc /path/to/workspace
#
# Recursively load all RC files, starting at /
function load_rc {
	local BASE=$(dirname $(readlink -f "${1}"))
	while [ "${BASE}" !=  "/" ]; do
		if [ -f "${BASE}"/.gtwsrc ]; then
			load_rc "${BASE}"
			echo "Loading ${BASE}/.gtwsrc"
			source "${BASE}"/.gtwsrc
			return 0
		fi
		BASE=$(readlink -f $(dirname "${BASE}"))
	done

	# Stop at /
	return 1
}

# title "foobar"
#
# Set the xterm/gnome-terminal title
function title {
	 echo -en "\033]2;$1\007"
}

# Load config files
load_rc ${WSPATH}

if [ -z "${GTWS_SAVEPATH}" ]; then
	export GTWS_SAVEPATH="${PATH}"
fi
if [ -n "${GTWS_PATH_EXTRA}" ]; then
	export PATH=$GTWS_SAVEPATH:"${GTWS_PATH_EXTRA}"
fi

export CDPATH=":$WSPATH"

title "${GTWS_PROJECT_VERSION}-${WSNAME}"

if [ -z "${GTWS_SAVEPS1}" ]; then
	export GTWS_SAVEPS1="${PS1}"
fi
if [ -n "${GTWS_SETPROMPT}" ]; then
	PROMPT="($GTWS_PROJECT"
	if [ "$GTWS_PROJECT_VERSION" != "trunk" ]; then
		PROMPT="${PROMPT}-${GTWS_PROJECT_VERSION}"
	fi
	PROMPT="${PROMPT}-${WSNAME})"
fi
PS1="${PROMPT}${GTWS_SAVEPS1}"

# Local settings go here
