#!/bin/bash
#
# Recursively make tags file for all c, cpp, C, c++, h files
#

USAGE="[-hkecpj] [<directories>]"
LONGUSAGE="\t-h\tPrint this help message
\t-k\tKernel database (no system includes)
\t-e\tEmtpy build (no .maketagsrc)
\t-c\tOnly tag C/C++
\t-p\tOnly tag perl and python
\t-j\tOnly tag java
\t<directories>\tDirectories to scan (defaults to '.')"

GTWSLOC=$(readlink -f $(dirname "$0"))
source ${GTWSLOC}/gtws.sh

while getopts ":hkecpj" option; do
	case ${option} in
		e ) CLEAN="-e";;
		c ) CPP="-c";;
		k ) KERNEL="-k";;
		p ) PERL="-p";;
		j ) JAVA="-j";;
		h ) usage;;
		\? ) usage "Invalid argument ${OPTARG}";;
		* ) usage "Invalid argument ${option}";;
	esac
done

# Store how we got here, so vim can re-run the same arguments
echo "$0 $@" > ".#maketags.dfg"

# Get stuff from the .maketagsrc file
if [ -z "${CLEAN}" ]; then
	if [ -f ".gtwsrc" ]; then
		source ".gtwsrc"
	elif [ -f "${HOME}/.maketagsrc" ]; then
		source ${HOME}/.maketagsrc
	fi
fi

if [ "${OPTIND}" != "0" ]; then
	shift $((OPTIND-1))
fi

if [ -z "$1" ]; then
	DIRS="."
else
	DIRS="$@"
fi

if [ -n "${KERNEL}" ]; then
	echo "Making kernel tags for $DIRS"
	HDRS="${KERNEL_HDRS}"
else
	echo "Making tags for $DIRS"
	HDRS="${SYSTEM_HDRS}"
fi

TMPFILE=`mktemp -t maketags.XXXXXXXXXX` || die "Couldn't make tempfile"

if [ -n "${CPP}" ]; then
	if [ -n "${HDRS}" ]; then
		find ${HDRS} -type f -and \( -name "*.h++" -or -name "*.hxx" -or -name "*.hh" -or -name "*.hpp" -or -name "*.H" -or -name "*.h" \) >> ${TMPFILE}
	fi
	find ${DIRS} ${EXTRA_DIRS} -type f -and \( -name "*.c" -or -name "*.cpp" -or -name "*.cxx" -or -name "*.h++" -or -name "*.hxx" -or -name "*.hh" -or -name "*.hpp" -or -name "*.H" -or -name "*.C" -or -name "*.c++" -or -name "*.cc" -or -name "*.h" \) >> ${TMPFILE}
	SUBSET="yes"
elif [ -n "${PERL}" ]; then
	find ${DIRS} -type f -and \( -name "*.pl" -or -name "*.pm" -or -name "*.perl"  -or -name "*.py" \) >> ${TMPFILE}
	SUBSET="yes"
elif [ -n "${JAVA}" ]; then
	find ${DIRS} -type f -and \( -name "*.java" \) >> ${TMPFILE}
	SUBSET="yes"
else
	find ${DIRS} -type f >> ${TMPFILE}
fi

if [ -n "${SKIPRE}" ]; then
	egrep -v "${SKIPRE}" ${TMPFILE} > cscope.files
	SUBSET="yes"
else
	egrep -v ".svn" ${TMPFILE} > cscope.files
fi
rm ${TMPFILE}
cscope -q -L ${KERNEL} -i cscope.files
if [ -n "${SUBSET}" ]; then
	# We're only using a subset of files; use files in the list
	ctags -L- < cscope.files
else
	# Tag everything, so that we get languages other than C/C++
	ctags -R
fi
