#!/bin/bash
#
# Create a new Project development workspace
#

function GTWScleanup {
	if [ -n "${MKWS_CLEANUP}" ]; then
		rm -rf "${GTWS_WSPATH}"
	fi
}

# Standard functions
GTWS_LOC=$(readlink -f $(dirname "$0"))
source ${GTWS_LOC}/gtws.sh

if [ -f "${PWD}/.gtwsrc" ]; then
	load_rc "${PWD}"
else
	source "${HOME}/.gtwsrc"
fi

if [ -n "${GTWS_PROJECT_VERSION}" ]; then
	VERSION="${GTWS_PROJECT_VERSION}"
elif [ -n "${GTWS_DEFAULT_PROJECT_VERSION}" ]; then
	VERSION="${GTWS_DEFAULT_PROJECT_VERSION}"
else
	VERSION=$(basename "$PWD");
fi

if [ -n "${GTWS_PROJECT}" ]; then
	PROJECT="${GTWS_PROJECT}"
elif [ -n "${GTWS_DEFAULT_PROJECT}" ]; then
	PROJECT="${GTWS_DEFAULT_PROJECT}"
else
	PROJECT=$(basename $(dirname "$PWD"));
fi

# Set usage output
USAGE="[-h |--help] [-p <project> | --project=<project>] [-v <version> | --version=<version>] [-V | --verbose] <name>"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t-p <project>, --project=<project>\n\t\tProject (default: ${PROJECT:-none})
\t-v <version>, --version=<version>\n\t\tProject version (default: ${VERSION})
\t-V, --verbose\n\t\tBe verbose
\t<name>\n\t\tWorkspace name"

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o hVp:v: --long help,verbose,project:,version: -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		-p|--project) PROJECT=$2 ; shift 2 ;;
		-v|--version) VERSION=$2 ; shift 2 ;;
		-V|--verbose) export GTWS_VERBOSE=yes; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

if [ -n "${GTWS_WS_GUARD}" ]; then
	usage "Cannot create workspace in an existng workspace"
fi

# Remaining arguments are in $1, $2, etc. as normal
if [ -z "${1}" ]; then
	usage "Must give a workspace name"
fi

if [ -z "${PROJECT}" ]; then
	usage "Must give a project"
fi

if [ -z "${GTWS_PROJECT}" ]; then
	# We weren't in a project directory; go there
	BASE="${GTWS_BASE_SRCDIR:-${HOME}/src}/${PROJECT}/${VERSION}"
	cd "${BASE}" || die "Couldn't cd to project dir ${BASE}"
elif [ "${PROJECT}" != "${GTWS_PROJECT}" ]; then
	die "In wrong project dir: expected ${PROJECT} got ${GTWS_PROJECT}"
fi

GTWS_WSPATH=$(readlink -f "${1}")
GTWS_WSNAME=$(basename "${GTWS_WSPATH}")

# Target directory check
if [ -d "${GTWS_WSPATH}" ]; then
	die "Workspace ${GTWS_WSPATH} already exists"
fi

# From here on out, clean up on failure
MKWS_CLEANUP="yes"

# Set up the environment
mkdir -p "${GTWS_WSPATH}" || die "Failed to mkdir ${GTWS_WSPATH}"
cd "${GTWS_WSPATH}"
cp "${GTWS_LOC}"/gtwsrc "${GTWS_WSPATH}"/.gtwsrc
source "${GTWS_WSPATH}"/.gtwsrc

# Origin
O="${GTWS_ORIGIN:=${HOME}/origin}"

HAS_CLONE=$(declare -F | grep "\<gtws_project_clone\>")
if [ -z "${HAS_CLONE}" ]; then
	gtws_opv "${O}" "${PROJECT}" "${VERSION}" opv

	# Workspace contents check
	repos=${GTWS_PROJECT_REPOS}
	if [ -z "${repos}" ]; then
		for i in "${opv}"/*; do
			if is_git_repo "$i"; then
				repos="$(basename $i) $repos"
			fi
		done
	fi
	for repo in ${repos}; do
		rpath="${opv}/${repo}"
		if ! is_git_repo "$rpath"; then
			rpath="${opv}/${repo}.git"
			if ! is_git_repo "$rpath"; then
				die "${rpath} in origin ${opv} is not git"
			fi
		fi
	done

	if [ -z "${repos}" ]; then
		die "No git repos in origin ${O}/${PROJECT}/${VERSION}"
	fi
	export GTWS_PROJECT_REPOS=${repos}
fi

# Make workspace
echo "Making workspace for ${VERSION}:${TARGET} in ${GTWS_WSPATH}"
# Made directory above

touch "${GTWS_WSPATH}/.sdirs"

if [ -n "${HAS_CLONE}" ]; then
	# Project provided a clone
	gtws_project_clone "${O}" "${PROJECT}" "${VERSION}" "${GTWS_WSNAME}" "${GTWS_SUBMODULE_ORIGIN}" || die "clone failed"
else
	# Default clone
	gtws_project_clone_default "${O}" "${PROJECT}" "${VERSION}" "${GTWS_WSNAME}" "${GTWS_SUBMODULE_ORIGIN}" || die "clone failed"
fi

if [ -n "$(declare -F | grep "\<gtws_project_setup\>")" ]; then
	gtws_project_setup "${GTWS_WSNAME}" "${O}" "${PROJECT}" "${VERSION}" || die "setup failed"
else
	gtws_project_setup_default "${GTWS_WSNAME}" "${O}" "${PROJECT}" "${VERSION}" || die "setup failed"
fi

echo "Done"
