#!/bin/bash
#
# Delete project development workspace
#

VERSION=$(basename "${PWD}")
PROJECT=$(basename $(dirname "$PWD"));

# Set usage output
USAGE="[-h |--help] <name>"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t<name>\n\t\tWorkspace name"

# Standard functions
GTWSLOC=$(readlink -f $(dirname "$0"))
source ${GTWSLOC}/gtws.sh

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o h --long help -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal
if [ -z "${1}" ]; then
	usage "Must give a workspace name"
fi

WSPATH=$(readlink -f "${1}")
WSNAME=$(basename "${WSPATH}")

# Target directory check
if [ ! -d "${WSPATH}" ]; then
	die "Workspace ${WSPATH} doesn't exist"
fi

# Cleanup
if [ -n "$(declare -F | grep "gtws_project_cleanup")" ]; then
	basedir="${PWD}"
	cd "${WSPATH}"
	gtws_project_cleanup ${WSNAME} ${PROJECT} ${VERSION} || die "cleanup failed"
	cd "${basedir}"
fi

# Nuke workspace
rm -rf "${WSPATH}"
