#!/bin/bash
#
# Delete GateD development workspace
#

GATED=$(basename "${PWD}")

WSBASE="${HOME}/origin"
WSDIRS="routing docs gatt"

# Set usage output
USAGE="[-h |--help] <name>"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t<name>\n\t\tWorkspace name"

# Standard functions
die() {
	echo "$@"
	exit 1
}

usage() {
	local myusage;
	if [ -n "${USAGE}" ]; then
		myusage=${USAGE}
	else
		myusage="No usage given"
	fi
	if [ -n "$1" ]; then
		echo "$@"
	fi
	echo ""
	echo "Usage:"
	echo "`basename $0` ${myusage}"
	if [ -n "${LONGUSAGE}" ]; then
		echo -e "${LONGUSAGE}"
	fi
	exit 1
}

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o h --long help -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal
if [ -z "${1}" ]; then
	usage "Must give a workspace name"
fi

WSPATH=$(readlink -f "${1}")
WSNAME=$(basename "${WSPATH}")

# Target directory check
if [ ! -d "${WSPATH}" ]; then
	die "Workspace ${WSPATH} doesn't exist"
fi

# Nuke workspace
rm -rf "${WSPATH}"
# Nuke workdir
rm -rf "/casa/${USER}/test/working/${GATED}/${WSNAME}"
