#!/bin/bash
#
# Clone an rtos into a workspace
#

WSBASE="${GTWS_ORIGIN:-${HOME}/origin}"
WSPATH="${PWD}"

# Set usage output
USAGE="[-h |--help] [-a | --all-rtos] <rtos> [<rtos> ...]"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t-a, --all-rtos\n\t\t Get all rtos versions
\t<rtos>\n\t\tRTOS version"

# Standard functions
source ${GTWS}/gtws.sh

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o ha --long help,all: -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		-a|--all-rtos) ALL="yes"; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal

if [ -n "${1}" ]; then
	RTOS=${@}
fi

if [ -n "${ALL}" ]; then
	cd "${WSBASE}"
	RTOS=$(/bin/ls -d i*)
fi

if [ -z "${RTOS}" ]; then
	usage "Must give an rtos version"
fi

cd "${WSPATH}"

for i in ${RTOS}; do
	echo "cloning $i"
	git clone "${WSBASE}/${i}" || die "failed to clone ${i}"
	cp "${WSBASE}/${i}/.git/info/exclude" "${i}/.git/info/" || die "failed to copy exclude"
	echo "Setting up $i"
	cd "${WSPATH}/${i}/modules/ghs" || die "failed to cd to ${i}/modules/ghs"
	ln -s "${WSPATH}/routing" "gated" || die "failed to symlink gated"
	cd "${WSPATH}/${i}" || die "failed to cd to ${i}"
	./setup > /dev/null 2>&1
	cd "${WSPATH}"
	echo ""
done

