#!/bin/bash
#
# Start session in a workspace
#

SAVEVARS="LOC PROJECT PROJECT_VERSION VERBOSE WSNAME"

# Standard functions
GTWS_LOC=$(readlink -f $(dirname "$0"))
source ${GTWS_LOC}/gtws.sh

if [ -f "${PWD}/.gtwsrc" ]; then
	debug_print "startws: loading ${PWD}"
	load_rc "${PWD}"
else
	debug_print "startws: sourcing Top"
	source "${HOME}/.gtwsrc"
fi

if [ -n "${GTWS_PROJECT_VERSION}" ]; then
	VERSION="${GTWS_PROJECT_VERSION}"
elif [ -n "${GTWS_DEFAULT_PROJECT_VERSION}" ]; then
	VERSION="${GTWS_DEFAULT_PROJECT_VERSION}"
else
	VERSION=$(basename "$PWD");
fi

if [ -n "${GTWS_PROJECT}" ]; then
	PROJECT="${GTWS_PROJECT}"
elif [ -n "${GTWS_DEFAULT_PROJECT}" ]; then
	PROJECT="${GTWS_DEFAULT_PROJECT}"
else
	PROJECT=$(basename $(dirname "$PWD"));
fi

# Set usage output
USAGE="[-h |--help] [-p <project> | --project=<project>] [-v <version> | --version=<version>] [-V | --verbose] <name>"
LONGUSAGE="\t-h, --help\n\t\tPrint this help message
\t-p <project>, --project=<project>\n\t\tProject (default: ${PROJECT:-none})
\t-v <version>, --version=<version>\n\t\tProject version (default: ${VERSION})
\t-V, --verbose\n\t\tBe verbose
\t<name>\n\t\tWorkspace name"

# Script name
ME=$(basename $0)

# Parse arguments
ARGS=`getopt -o hVp:v: --long help,verbose,project:,version: -n "${ME}" -- "$@"`

if [ $? != 0 ] ; then
	usage 
fi
eval set -- "$ARGS"

while true ; do
	case "$1" in
		-h|--help) usage; shift ;;
		-p|--project) PROJECT=$2 ; shift 2 ;;
		-v|--version) VERSION=$2 ; shift 2 ;;
		-V|--verbose) export GTWS_VERBOSE=yes; shift ;;
		--) shift ; break ;;
		* ) usage "Invalid argument $1";;
	esac
done

# Remaining arguments are in $1, $2, etc. as normal
if [ -n "${1}" ]; then
	GTWS_WSNAME="${1%/}"
fi

if [ -z "${GTWS_WSNAME}" ]; then
	usage "Must be in a workspace or give a workspace name"
fi

if [ -z "${PROJECT}" ]; then
	usage "Must be in a project or give a project name"
fi

BASE=${GTWS_BASE_SRCDIR:-${HOME}/src}

if [ ! -f "${BASE}/${PROJECT}/${VERSION}/${GTWS_WSNAME}/.gtwsrc" ]; then
	usage "No .gtwsrc for ${PROJECT}/${VERSION}/${GTWS_WSNAME}"
fi

# Save variables
for i in ${SAVEVARS}; do
	SRC=GTWS_${i}
	DST=SAVE_${i}
	debug_print "\t $i: ${DST} = ${!SRC}"
	eval ${DST}=${!SRC}
done

# Clear GTWS evironment
for i in ${!GTWS*} ; do
	debug_print "unset $i"
	unset $i
done

# Restore variables
for i in ${SAVEVARS}; do
	SRC=SAVE_${i}
	DST=GTWS_${i}
	debug_print "\t $i: ${DST} = ${!SRC}"
	eval export ${DST}=${!SRC}
done

cd "${BASE}/${PROJECT}/${VERSION}/${GTWS_WSNAME}"
debug_print "exec bash --rcfile ${BASE}/${PROJECT}/${VERSION}/${GTWS_WSNAME}/.gtwsrc"
exec bash --rcfile ${BASE}/${PROJECT}/${VERSION}/${GTWS_WSNAME}/.gtwsrc
